services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ecommerce_laravel_app

    ports:
      - "8085:8000"

    volumes:
      - .:/var/www/html

    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://127.0.0.1:8085

      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ecommerce
      DB_USERNAME: ecommerce
      DB_PASSWORD: ecommerce_password

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - ecommerce_network


  mysql:
    image: mysql:8.0

    container_name: ecommerce_laravel_mysql

    restart: unless-stopped

    ports:
      - "3307:3306"

    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecommerce
      MYSQL_PASSWORD: ecommerce_password
      MYSQL_ROOT_PASSWORD: ecommerce_root_password

    volumes:
      - ecommerce_mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-pecommerce_root_password"
        ]
      interval: 5s
      timeout: 5s
      retries: 20

    networks:
      - ecommerce_network


  node:
    image: node:20

    container_name: ecommerce_laravel_node

    working_dir: /var/www/html

    volumes:
      - .:/var/www/html

    command: sh -c "npm install --legacy-peer-deps && npm run watch-poll"

    networks:
      - ecommerce_network


networks:

  ecommerce_network:
    name: ecommerce_laravel_network
    driver: bridge


volumes:

  ecommerce_mysql_data:
    name: ecommerce_laravel_mysql_data
